name: 'DX Scanner Action'
description: 'Measure Developer Experience directly based on your source code'
icon: user-check
color: green
inputs:
  github_token:
    description: 'Github API token (https://github.com/settings/tokens/new)'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.github_token }}

