/* eslint-disable @typescript-eslint/camelcase */
export const getIssueResponse = {
  url: 'https://api.github.com/repos/octocat/Hello-World/issues/1',
  repository_url: 'https://api.github.com/repos/octocat/Hello-World',
  labels_url: 'https://api.github.com/repos/octocat/Hello-World/issues/1/labels{/name}',
  comments_url: 'https://api.github.com/repos/octocat/Hello-World/issues/1/comments',
  events_url: 'https://api.github.com/repos/octocat/Hello-World/issues/1/events',
  html_url: 'https://github.com/octocat/Hello-World/pull/1',
  id: 872858,
  node_id: 'MDExOlB1bGxSZXF1ZXN0MTQwOTAw',
  number: 1,
  title: 'Edited README via GitHub',
  user: {
    login: 'unoju',
    id: 777449,
    node_id: 'MDQ6VXNlcjc3NzQ0OQ==',
    avatar_url: 'https://avatars2.githubusercontent.com/u/777449?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/unoju',
    html_url: 'https://github.com/unoju',
    followers_url: 'https://api.github.com/users/unoju/followers',
    following_url: 'https://api.github.com/users/unoju/following{/other_user}',
    gists_url: 'https://api.github.com/users/unoju/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/unoju/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/unoju/subscriptions',
    organizations_url: 'https://api.github.com/users/unoju/orgs',
    repos_url: 'https://api.github.com/users/unoju/repos',
    events_url: 'https://api.github.com/users/unoju/events{/privacy}',
    received_events_url: 'https://api.github.com/users/unoju/received_events',
    type: 'User',
    site_admin: false,
  },
  labels: [],
  state: 'closed',
  locked: false,
  assignee: null,
  assignees: [],
  milestone: null,
  comments: 28,
  created_at: '2011-05-09T19:10:00Z',
  updated_at: '2018-07-06T14:06:18Z',
  closed_at: '2011-05-18T20:00:25Z',
  author_association: 'NONE',
  pull_request: {
    url: 'https://api.github.com/repos/octocat/Hello-World/pulls/1',
    html_url: 'https://github.com/octocat/Hello-World/pull/1',
    diff_url: 'https://github.com/octocat/Hello-World/pull/1.diff',
    patch_url: 'https://github.com/octocat/Hello-World/pull/1.patch',
  },
  body: '',
  closed_by: {
    login: 'octocat',
    id: 583231,
    node_id: 'MDQ6VXNlcjU4MzIzMQ==',
    avatar_url: 'https://avatars3.githubusercontent.com/u/583231?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/octocat',
    html_url: 'https://github.com/octocat',
    followers_url: 'https://api.github.com/users/octocat/followers',
    following_url: 'https://api.github.com/users/octocat/following{/other_user}',
    gists_url: 'https://api.github.com/users/octocat/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/octocat/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/octocat/subscriptions',
    organizations_url: 'https://api.github.com/users/octocat/orgs',
    repos_url: 'https://api.github.com/users/octocat/repos',
    events_url: 'https://api.github.com/users/octocat/events{/privacy}',
    received_events_url: 'https://api.github.com/users/octocat/received_events',
    type: 'User',
    site_admin: false,
  },
};
