/* eslint-disable @typescript-eslint/camelcase */
export const getPullRequestsReviewsResponse = [
  {
    id: 41231978,
    node_id: 'MDE3OlB1bGxSZXF1ZXN0UmV2aWV3NDEyMzE5Nzg=',
    user: {
      login: 'pedrorijo91',
      id: 1999050,
      node_id: 'MDQ6VXNlcjE5OTkwNTA=',
      avatar_url: 'https://avatars2.githubusercontent.com/u/1999050?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/pedrorijo91',
      html_url: 'https://github.com/pedrorijo91',
      followers_url: 'https://api.github.com/users/pedrorijo91/followers',
      following_url: 'https://api.github.com/users/pedrorijo91/following{/other_user}',
      gists_url: 'https://api.github.com/users/pedrorijo91/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/pedrorijo91/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/pedrorijo91/subscriptions',
      organizations_url: 'https://api.github.com/users/pedrorijo91/orgs',
      repos_url: 'https://api.github.com/users/pedrorijo91/repos',
      events_url: 'https://api.github.com/users/pedrorijo91/events{/privacy}',
      received_events_url: 'https://api.github.com/users/pedrorijo91/received_events',
      type: 'User',
      site_admin: false,
    },
    body: '',
    state: 'COMMENTED',
    html_url: 'https://github.com/octocat/Hello-World/pull/1#pullrequestreview-41231978',
    pull_request_url: 'https://api.github.com/repos/octocat/Hello-World/pulls/1',
    author_association: 'NONE',
    _links: {
      html: {
        href: 'https://github.com/octocat/Hello-World/pull/1#pullrequestreview-41231978',
      },
      pull_request: {
        href: 'https://api.github.com/repos/octocat/Hello-World/pulls/1',
      },
    },
    submitted_at: '2017-05-31T13:49:01Z',
    commit_id: '7044a8a032e85b6ab611033b2ac8af7ce85805b2',
  },
  {
    id: 134751616,
    node_id: 'MDE3OlB1bGxSZXF1ZXN0UmV2aWV3MTM0NzUxNjE2',
    user: {
      login: 'alexanderclin',
      id: 13119311,
      node_id: 'MDQ6VXNlcjEzMTE5MzEx',
      avatar_url: 'https://avatars0.githubusercontent.com/u/13119311?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/alexanderclin',
      html_url: 'https://github.com/alexanderclin',
      followers_url: 'https://api.github.com/users/alexanderclin/followers',
      following_url: 'https://api.github.com/users/alexanderclin/following{/other_user}',
      gists_url: 'https://api.github.com/users/alexanderclin/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/alexanderclin/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/alexanderclin/subscriptions',
      organizations_url: 'https://api.github.com/users/alexanderclin/orgs',
      repos_url: 'https://api.github.com/users/alexanderclin/repos',
      events_url: 'https://api.github.com/users/alexanderclin/events{/privacy}',
      received_events_url: 'https://api.github.com/users/alexanderclin/received_events',
      type: 'User',
      site_admin: false,
    },
    body: '',
    state: 'COMMENTED',
    html_url: 'https://github.com/octocat/Hello-World/pull/1#pullrequestreview-134751616',
    pull_request_url: 'https://api.github.com/repos/octocat/Hello-World/pulls/1',
    author_association: 'NONE',
    _links: {
      html: {
        href: 'https://github.com/octocat/Hello-World/pull/1#pullrequestreview-134751616',
      },
      pull_request: {
        href: 'https://api.github.com/repos/octocat/Hello-World/pulls/1',
      },
    },
    submitted_at: '2018-07-05T17:43:22Z',
    commit_id: '7044a8a032e85b6ab611033b2ac8af7ce85805b2',
  },
  {
    id: 134757534,
    node_id: 'MDE3OlB1bGxSZXF1ZXN0UmV2aWV3MTM0NzU3NTM0',
    user: {
      login: 'jonathantsang',
      id: 19191220,
      node_id: 'MDQ6VXNlcjE5MTkxMjIw',
      avatar_url: 'https://avatars3.githubusercontent.com/u/19191220?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/jonathantsang',
      html_url: 'https://github.com/jonathantsang',
      followers_url: 'https://api.github.com/users/jonathantsang/followers',
      following_url: 'https://api.github.com/users/jonathantsang/following{/other_user}',
      gists_url: 'https://api.github.com/users/jonathantsang/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/jonathantsang/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/jonathantsang/subscriptions',
      organizations_url: 'https://api.github.com/users/jonathantsang/orgs',
      repos_url: 'https://api.github.com/users/jonathantsang/repos',
      events_url: 'https://api.github.com/users/jonathantsang/events{/privacy}',
      received_events_url: 'https://api.github.com/users/jonathantsang/received_events',
      type: 'User',
      site_admin: false,
    },
    body: '',
    state: 'COMMENTED',
    html_url: 'https://github.com/octocat/Hello-World/pull/1#pullrequestreview-134757534',
    pull_request_url: 'https://api.github.com/repos/octocat/Hello-World/pulls/1',
    author_association: 'NONE',
    _links: {
      html: {
        href: 'https://github.com/octocat/Hello-World/pull/1#pullrequestreview-134757534',
      },
      pull_request: {
        href: 'https://api.github.com/repos/octocat/Hello-World/pulls/1',
      },
    },
    submitted_at: '2018-07-05T17:59:11Z',
    commit_id: '7044a8a032e85b6ab611033b2ac8af7ce85805b2',
  },
  {
    id: 135027960,
    node_id: 'MDE3OlB1bGxSZXF1ZXN0UmV2aWV3MTM1MDI3OTYw',
    user: {
      login: 'jonathantsang',
      id: 19191220,
      node_id: 'MDQ6VXNlcjE5MTkxMjIw',
      avatar_url: 'https://avatars3.githubusercontent.com/u/19191220?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/jonathantsang',
      html_url: 'https://github.com/jonathantsang',
      followers_url: 'https://api.github.com/users/jonathantsang/followers',
      following_url: 'https://api.github.com/users/jonathantsang/following{/other_user}',
      gists_url: 'https://api.github.com/users/jonathantsang/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/jonathantsang/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/jonathantsang/subscriptions',
      organizations_url: 'https://api.github.com/users/jonathantsang/orgs',
      repos_url: 'https://api.github.com/users/jonathantsang/repos',
      events_url: 'https://api.github.com/users/jonathantsang/events{/privacy}',
      received_events_url: 'https://api.github.com/users/jonathantsang/received_events',
      type: 'User',
      site_admin: false,
    },
    body: '',
    state: 'COMMENTED',
    html_url: 'https://github.com/octocat/Hello-World/pull/1#pullrequestreview-135027960',
    pull_request_url: 'https://api.github.com/repos/octocat/Hello-World/pulls/1',
    author_association: 'NONE',
    _links: {
      html: {
        href: 'https://github.com/octocat/Hello-World/pull/1#pullrequestreview-135027960',
      },
      pull_request: {
        href: 'https://api.github.com/repos/octocat/Hello-World/pulls/1',
      },
    },
    submitted_at: '2018-07-06T14:06:18Z',
    commit_id: '7044a8a032e85b6ab611033b2ac8af7ce85805b2',
  },
];
