/* eslint-disable @typescript-eslint/camelcase */
export const getPullCommitsResponse = [
  {
    sha: '7044a8a032e85b6ab611033b2ac8af7ce85805b2',
    node_id: 'MDY6Q29tbWl0MTcyNDE5NTo3MDQ0YThhMDMyZTg1YjZhYjYxMTAzM2IyYWM4YWY3Y2U4NTgwNWIy',
    commit: {
      author: {
        name: 'unoju',
        email: 'myemailismels@yahoo.com',
        date: '2011-05-09T19:09:20Z',
      },
      committer: {
        name: 'unoju',
        email: 'myemailismels@yahoo.com',
        date: '2011-05-09T19:09:20Z',
      },
      message: 'Edited README via GitHub',
      tree: {
        sha: 'f1b625880dea0b3af9168f3537838d2607217460',
        url: 'https://api.github.com/repos/octocat/Hello-World/git/trees/f1b625880dea0b3af9168f3537838d2607217460',
      },
      url: 'https://api.github.com/repos/octocat/Hello-World/git/commits/7044a8a032e85b6ab611033b2ac8af7ce85805b2',
      comment_count: 0,
      verification: {
        verified: false,
        reason: 'unsigned',
        signature: null,
        payload: null,
      },
    },
    url: 'https://api.github.com/repos/octocat/Hello-World/commits/7044a8a032e85b6ab611033b2ac8af7ce85805b2',
    html_url: 'https://github.com/octocat/Hello-World/commit/7044a8a032e85b6ab611033b2ac8af7ce85805b2',
    comments_url: 'https://api.github.com/repos/octocat/Hello-World/commits/7044a8a032e85b6ab611033b2ac8af7ce85805b2/comments',
    author: {
      login: 'unoju',
      id: 777449,
      node_id: 'MDQ6VXNlcjc3NzQ0OQ==',
      avatar_url: 'https://avatars2.githubusercontent.com/u/777449?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/unoju',
      html_url: 'https://github.com/unoju',
      followers_url: 'https://api.github.com/users/unoju/followers',
      following_url: 'https://api.github.com/users/unoju/following{/other_user}',
      gists_url: 'https://api.github.com/users/unoju/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/unoju/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/unoju/subscriptions',
      organizations_url: 'https://api.github.com/users/unoju/orgs',
      repos_url: 'https://api.github.com/users/unoju/repos',
      events_url: 'https://api.github.com/users/unoju/events{/privacy}',
      received_events_url: 'https://api.github.com/users/unoju/received_events',
      type: 'User',
      site_admin: false,
    },
    committer: {
      login: 'unoju',
      id: 777449,
      node_id: 'MDQ6VXNlcjc3NzQ0OQ==',
      avatar_url: 'https://avatars2.githubusercontent.com/u/777449?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/unoju',
      html_url: 'https://github.com/unoju',
      followers_url: 'https://api.github.com/users/unoju/followers',
      following_url: 'https://api.github.com/users/unoju/following{/other_user}',
      gists_url: 'https://api.github.com/users/unoju/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/unoju/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/unoju/subscriptions',
      organizations_url: 'https://api.github.com/users/unoju/orgs',
      repos_url: 'https://api.github.com/users/unoju/repos',
      events_url: 'https://api.github.com/users/unoju/events{/privacy}',
      received_events_url: 'https://api.github.com/users/unoju/received_events',
      type: 'User',
      site_admin: false,
    },
    parents: [
      {
        sha: '553c2077f0edc3d5dc5d17262f6aa498e69d6f8e',
        url: 'https://api.github.com/repos/octocat/Hello-World/commits/553c2077f0edc3d5dc5d17262f6aa498e69d6f8e',
        html_url: 'https://github.com/octocat/Hello-World/commit/553c2077f0edc3d5dc5d17262f6aa498e69d6f8e',
      },
    ],
  },
];
