export enum ErrorCode {
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  SERVICE_ERROR = 'SERVICE_ERROR',
  ARGUMENT_ERROR = 'ARGUMENT_ERROR',
  AUTHORIZATION_ERROR = 'AUTHORIZATION_ERROR',
  NOT_IMPLEMENTED_ERROR = 'NOT_IMPLEMENTED_ERROR',
}
