import { UserItem, Repository, BranchItem } from '../../../../../test/helpers/gitHubNock';

/* eslint-disable @typescript-eslint/camelcase */
export const getPullRequestResponse = {
  url: 'https://api.github.com/repos/octocat/Hello-World/pulls/1',
  id: 140900,
  node_id: 'MDExOlB1bGxSZXF1ZXN0MTQwOTAw',
  html_url: 'https://github.com/octocat/Hello-World/pull/1',
  diff_url: 'https://github.com/octocat/Hello-World/pull/1.diff',
  patch_url: 'https://github.com/octocat/Hello-World/pull/1.patch',
  issue_url: 'https://api.github.com/repos/octocat/Hello-World/issues/1',
  number: 1,
  state: 'closed',
  locked: false,
  title: 'Edited README via GitHub',
  user: new UserItem(777449, 'unoju'),
  body: '',
  created_at: '2011-05-09T19:10:00Z',
  updated_at: '2018-07-06T14:06:18Z',
  closed_at: '2011-05-18T20:00:25Z',
  merged_at: null,
  merge_commit_sha: 'f13731c44acf96f2e5d6f0080f54e09215e36248',
  assignee: null,
  assignees: [],
  requested_reviewers: [],
  requested_teams: [],
  labels: [],
  milestone: null,
  commits_url: 'https://api.github.com/repos/octocat/Hello-World/pulls/1/commits',
  review_comments_url: 'https://api.github.com/repos/octocat/Hello-World/pulls/1/comments',
  review_comment_url: 'https://api.github.com/repos/octocat/Hello-World/pulls/comments{/number}',
  comments_url: 'https://api.github.com/repos/octocat/Hello-World/issues/1/comments',
  statuses_url: 'https://api.github.com/repos/octocat/Hello-World/statuses/7044a8a032e85b6ab611033b2ac8af7ce85805b2',
  head: new BranchItem('patch-1', new Repository(1724195, 'Hello-World', new UserItem(777449, 'unoju'))),
  base: new BranchItem('master', new Repository(1296269, 'Hello-World', new UserItem(583231, 'octocat'))),
  _links: {
    self: {
      href: 'https://api.github.com/repos/octocat/Hello-World/pulls/1',
    },
    html: {
      href: 'https://github.com/octocat/Hello-World/pull/1',
    },
    issue: {
      href: 'https://api.github.com/repos/octocat/Hello-World/issues/1',
    },
    comments: {
      href: 'https://api.github.com/repos/octocat/Hello-World/issues/1/comments',
    },
    review_comments: {
      href: 'https://api.github.com/repos/octocat/Hello-World/pulls/1/comments',
    },
    review_comment: {
      href: 'https://api.github.com/repos/octocat/Hello-World/pulls/comments{/number}',
    },
    commits: {
      href: 'https://api.github.com/repos/octocat/Hello-World/pulls/1/commits',
    },
    statuses: {
      href: 'https://api.github.com/repos/octocat/Hello-World/statuses/7044a8a032e85b6ab611033b2ac8af7ce85805b2',
    },
  },
  author_association: 'NONE',
  merged: false,
  mergeable: false,
  rebaseable: false,
  mergeable_state: 'dirty',
  merged_by: null,
  comments: 28,
  review_comments: 6,
  maintainer_can_modify: false,
  commits: 1,
  additions: 6,
  deletions: 1,
  changed_files: 1,
};
