export const CargoTomlContents = `
[package]
name = "foo"
version = "0.1.0"
authors = ["edward"]
edition = "2018"

[dependencies]
foo2 = "1"
bar = { path = "../bar" }
baz = { git = "https://example.com", branch = "master", optional = true }
qux = { version = "0.4", default-features = false, features = ["thing"] }

[target.'cfg(unix)'.dependencies]
quz = "0.1.2"

[[bin]]
name = "foo"
path = "src/foo/main.rs"
`;

export const CargoTomlWorkspaceContents = `
[workspace]
members = ["foo", "bar"]
`;

export const CargoLockContents = `
# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
[[package]]
name = "foo2"
version = "1.0.1"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "5c897df197d57c25b37df9d8fa2f93ddbfeee9ebd2264350ac79c8ec4b795885"
dependencies = [
 "num-traits",
]

[[package]]
name = "bar"
version = "0.1.0"

[[package]]
name = "foo"
version = "0.1.0"
dependencies = [
 "atoi",
 "bar",
 "itoa",
 "vulkayes-core",
]

[[package]]
name = "qux"
version = "0.4.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "dc6f3ad7b9d11a0c00842ff8de1b60ee58661048eb8049ed33c73594f359d7e6"
`;
